begin;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null check (char_length(username) between 3 and 32),
  body text not null check (char_length(body) between 1 and 600),
  created_at timestamptz not null default now()
);

create index if not exists chat_messages_created_at_idx
  on public.chat_messages (created_at desc);

alter table public.chat_messages enable row level security;
revoke all on public.chat_messages from anon, authenticated;
grant select on public.chat_messages to authenticated;
grant usage, select on sequence public.chat_messages_id_seq to authenticated;

drop policy if exists "Account holders read chat" on public.chat_messages;
create policy "Account holders read chat"
  on public.chat_messages
  for select
  to authenticated
  using (true);

drop policy if exists "Account holders write own chat messages" on public.chat_messages;

create or replace function public.send_chat_message(message_body text, display_name text)
returns public.chat_messages
language plpgsql
security definer
set search_path = ''
as $$
declare
  created_message public.chat_messages;
  safe_body text := left(trim(message_body), 600);
  safe_name text := left(trim(display_name), 32);
  recent_count integer;
begin
  if auth.uid() is null then
    raise exception 'authentication_required';
  end if;
  if char_length(safe_body) < 1 or char_length(safe_name) < 3 then
    raise exception 'invalid_message';
  end if;

  select count(*) into recent_count
  from public.chat_messages
  where user_id = auth.uid() and created_at > now() - interval '30 seconds';
  if recent_count >= 5 then
    raise exception 'chat_rate_limited';
  end if;

  select count(*) into recent_count
  from public.chat_messages
  where user_id = auth.uid() and created_at > now() - interval '1 hour';
  if recent_count >= 80 then
    raise exception 'chat_rate_limited';
  end if;

  insert into public.chat_messages (user_id, username, body)
  values (auth.uid(), safe_name, safe_body)
  returning * into created_message;
  return created_message;
end;
$$;

revoke all on function public.send_chat_message(text, text) from public, anon;
grant execute on function public.send_chat_message(text, text) to authenticated;

create table if not exists public.reviews (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  username text not null check (char_length(username) between 3 and 32),
  rating smallint not null check (rating between 4 and 5),
  body text not null check (char_length(body) between 8 and 800),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.reviews enable row level security;
revoke all on public.reviews from anon, authenticated;
grant select on public.reviews to anon, authenticated;
grant insert, update on public.reviews to authenticated;

drop policy if exists "Reviews are public" on public.reviews;
create policy "Reviews are public"
  on public.reviews
  for select
  to anon, authenticated
  using (true);

drop policy if exists "Account holders create their review" on public.reviews;
create policy "Account holders create their review"
  on public.reviews
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Account holders update their review" on public.reviews;
create policy "Account holders update their review"
  on public.reviews
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop trigger if exists reviews_set_updated_at on public.reviews;
create trigger reviews_set_updated_at
before update on public.reviews
for each row execute function public.set_updated_at();

create table if not exists public.chess_games (
  id uuid primary key default gen_random_uuid(),
  white_id uuid not null references auth.users(id) on delete cascade,
  black_id uuid references auth.users(id) on delete set null,
  white_name text not null check (char_length(white_name) between 3 and 32),
  black_name text check (black_name is null or char_length(black_name) between 3 and 32),
  fen text not null default 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1'
    check (char_length(fen) between 20 and 120),
  pgn text not null default '' check (char_length(pgn) <= 12000),
  turn text not null default 'w' check (turn in ('w', 'b')),
  status text not null default 'waiting' check (status in ('waiting', 'active', 'finished')),
  winner_id uuid references auth.users(id) on delete set null,
  result text check (result is null or result in ('white', 'black', 'draw', 'resigned')),
  last_move text check (last_move is null or char_length(last_move) between 4 and 5),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint chess_players_are_different check (black_id is null or black_id <> white_id)
);

create index if not exists chess_games_status_updated_idx
  on public.chess_games (status, updated_at desc);

alter table public.chess_games enable row level security;
revoke all on public.chess_games from anon, authenticated;
grant select on public.chess_games to authenticated;

drop policy if exists "Account holders read chess games" on public.chess_games;
create policy "Account holders read chess games"
  on public.chess_games
  for select
  to authenticated
  using (true);

drop trigger if exists chess_games_set_updated_at on public.chess_games;
create trigger chess_games_set_updated_at
before update on public.chess_games
for each row execute function public.set_updated_at();

create or replace function public.create_chess_game(player_name text)
returns public.chess_games
language plpgsql
security definer
set search_path = ''
as $$
declare
  created_game public.chess_games;
  safe_name text := left(trim(player_name), 32);
begin
  if auth.uid() is null then
    raise exception 'authentication_required';
  end if;
  if char_length(safe_name) < 3 then
    raise exception 'invalid_player_name';
  end if;
  if (
    select count(*)
    from public.chess_games
    where white_id = auth.uid() and status in ('waiting', 'active')
  ) >= 5 then
    raise exception 'too_many_open_games';
  end if;

  insert into public.chess_games (white_id, white_name)
  values (auth.uid(), safe_name)
  returning * into created_game;
  return created_game;
end;
$$;

create or replace function public.join_chess_game(game_id uuid, player_name text)
returns public.chess_games
language plpgsql
security definer
set search_path = ''
as $$
declare
  joined_game public.chess_games;
  safe_name text := left(trim(player_name), 32);
begin
  if auth.uid() is null then
    raise exception 'authentication_required';
  end if;
  if char_length(safe_name) < 3 then
    raise exception 'invalid_player_name';
  end if;

  update public.chess_games
  set black_id = auth.uid(),
      black_name = safe_name,
      status = 'active'
  where id = game_id
    and status = 'waiting'
    and black_id is null
    and white_id <> auth.uid()
  returning * into joined_game;

  if joined_game.id is null then
    raise exception 'game_not_available';
  end if;
  return joined_game;
end;
$$;

create or replace function public.play_chess_move(
  game_id uuid,
  previous_fen text,
  next_fen text,
  next_pgn text,
  next_turn text,
  move_uci text,
  game_result text default null
)
returns public.chess_games
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_game public.chess_games;
  updated_game public.chess_games;
  expected_player uuid;
begin
  if auth.uid() is null then
    raise exception 'authentication_required';
  end if;
  if char_length(next_fen) not between 20 and 120
     or char_length(next_pgn) > 12000
     or next_turn not in ('w', 'b')
     or move_uci !~ '^[a-h][1-8][a-h][1-8][qrbn]?$'
     or (game_result is not null and game_result not in ('white', 'black', 'draw')) then
    raise exception 'invalid_move_payload';
  end if;

  select * into current_game
  from public.chess_games
  where id = game_id
  for update;

  if current_game.id is null or current_game.status <> 'active' or current_game.fen <> previous_fen then
    raise exception 'stale_game';
  end if;

  expected_player := case when current_game.turn = 'w' then current_game.white_id else current_game.black_id end;
  if expected_player is distinct from auth.uid() then
    raise exception 'not_your_turn';
  end if;

  update public.chess_games
  set fen = next_fen,
      pgn = next_pgn,
      turn = next_turn,
      last_move = move_uci,
      status = case when game_result is null then 'active' else 'finished' end,
      result = game_result,
      winner_id = case
        when game_result = 'white' then current_game.white_id
        when game_result = 'black' then current_game.black_id
        else null
      end
  where id = game_id
  returning * into updated_game;

  return updated_game;
end;
$$;

create or replace function public.resign_chess_game(game_id uuid)
returns public.chess_games
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_game public.chess_games;
  updated_game public.chess_games;
begin
  if auth.uid() is null then
    raise exception 'authentication_required';
  end if;

  select * into current_game
  from public.chess_games
  where id = game_id
  for update;

  if current_game.id is null
     or current_game.status <> 'active'
     or auth.uid() not in (current_game.white_id, current_game.black_id) then
    raise exception 'game_not_available';
  end if;

  update public.chess_games
  set status = 'finished',
      result = 'resigned',
      winner_id = case when auth.uid() = current_game.white_id then current_game.black_id else current_game.white_id end
  where id = game_id
  returning * into updated_game;
  return updated_game;
end;
$$;

revoke all on function public.create_chess_game(text) from public, anon;
revoke all on function public.join_chess_game(uuid, text) from public, anon;
revoke all on function public.play_chess_move(uuid, text, text, text, text, text, text) from public, anon;
revoke all on function public.resign_chess_game(uuid) from public, anon;
grant execute on function public.create_chess_game(text) to authenticated;
grant execute on function public.join_chess_game(uuid, text) to authenticated;
grant execute on function public.play_chess_move(uuid, text, text, text, text, text, text) to authenticated;
grant execute on function public.resign_chess_game(uuid) to authenticated;

do $$
begin
  alter publication supabase_realtime add table public.chat_messages;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.chess_games;
exception when duplicate_object then null;
end $$;

commit;
